# Generated by Django 4.1.2 on 2022-11-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artise',
            name='first_name',
            field=models.CharField(default='from datetime import datetime', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artise',
            name='last_name',
            field=models.CharField(default='from datetime import datetime', max_length=50),
            preserve_default=False,
        ),
    ]
